import {
  ArrowDownCircle,
  ArrowUpCircle,
  ArrowUpRight,
  ArrowDownRight,
  CreditCard,
  Repeat,
  Receipt,
  Circle,
  DollarSign,
  BarChart,
  Users,
  Calendar,
  Settings,
  Shield,
  HelpCircle,
  LogOut,
  User,
  Bell,
  Home,
  Wallet,
  PieChart,
  Banknote,
  Clock,
  CheckCircle,
  AlertCircle,
  XCircle,
  Plus,
  Minus,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  Search,
  Download,
  Upload,
  Copy,
  Edit,
  Trash,
  ExternalLink,
  Share2,
  Send,
  Eye,
  EyeOff,
  Save,
  X,
  Menu,
  type LucideIcon,
  type LucideProps,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  // Navigation
  home: Home,
  settings: Settings,
  help: HelpCircle,
  logout: LogOut,
  menu: Menu,
  close: X,
  
  // Transactions
  arrowDownCircle: ArrowDownCircle,
  arrowUpCircle: ArrowUpCircle,
  arrowUp: ArrowUpRight,
  arrowDown: ArrowDownRight,
  creditCard: CreditCard,
  repeat: Repeat,
  receipt: Receipt,
  circle: Circle,
  
  // Finance
  dollar: DollarSign,
  chart: BarChart,
  pieChart: PieChart,
  wallet: Wallet,
  banknote: Banknote,
  
  // Status
  checkCircle: CheckCircle,
  alertCircle: AlertCircle,
  xCircle: XCircle,
  
  // User
  user: User,
  users: Users,
  bell: Bell,
  security: Shield,
  calendar: Calendar,
  clock: Clock,
  
  // Actions
  plus: Plus,
  minus: Minus,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  search: Search,
  download: Download,
  upload: Upload,
  copy: Copy,
  edit: Edit,
  trash: Trash,
  externalLink: ExternalLink,
  share: Share2,
  send: Send,
  eye: Eye,
  eyeOff: EyeOff,
  save: Save,
}; 